services:
  - type: web
    name: eventforge
    runtime: node
    buildCommand: npm run build
    startCommand: node Backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
